# Generated by Django 3.1.7 on 2021-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_subscription', models.ManyToManyField(blank=True, related_name='subscribers', to='blog.BlogCategory')),
            ],
        ),
    ]
