# Generated by Django 3.1.7 on 2021-06-24 18:52

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='carousel_images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
    ]
