# Generated by Django 3.1.7 on 2021-06-24 19:02

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_project_carousel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='carousel_images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
