# Generated by Django 3.1.7 on 2021-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210624_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discord_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
