# Generated by Django 3.1.7 on 2021-06-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210627_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLinks',
            new_name='FooterLink',
        ),
    ]
