# Generated by Django 3.1.7 on 2021-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210627_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='link_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
